### ISSUE TITLE
wallpaper is only changed on the active desktop

### ISSUE THREAD

**Issue by luca-scr** [jonbeebe/MacDynamicWallpaper#1]
First of all, I would like to thank you for the script made available on GitHub.
I usually have 4 desktops and I would like to change the wallpaper on all the desktop at once. However, the script seems to change only the active desktop, i.e. that where it is run. If I move the script editor to another desktop (or osascript from a terminal) than the wallpaper is changed on that desktop, and so on. 
In principle it should work, if I correctly understand the command "set theDesktops to a reference to every desktop", but in practice it doesn't.

**Comment by jonbeebe** [comment]
Hello @luca-scr , the script is originally forked from https://github.com/jonbeebe/MacDynamicWallpaper/blob/master and that's where the multiple desktop handling code comes from. I'll take a look to see if I can debug the issue.

**Comment by jonbeebe** [comment]
@luca-scr I looked into it, and "set theDesktops to a reference to every desktop" in AppleScript refers to separate monitor screens, not individual mission control spaces. Unfortunately, it seems there is no way to get the number of mission control spaces in AppleScript. If you or anyone has an suggestions I'm open to it, but until then I think this one can be closed as a "can't fix".
